name: cicd

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    

            
  DeployProd:
    name: Deploy to Production 
    runs-on: ubuntu-latest
    needs: [Build]
    environment: 
      name: Production 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

    - name: Switch to production branch
      run: | 
          git fetch --prune --unshallow
          git checkout production
          git pull origin staging
          git checkout production
          git rebase production
          git push origin production --force
      
      - name: Install databricks CLI
        run: |
            curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      - name: Update databricks repo
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks repos update /Workspace/Repos/shaswat.pandey@onebyzero.ai/databricks --branch production
    # - name: Merge changes from staging
    #   run: git merge staging --no-edit

    # - name: Push changes to production
    #   run: git push origin production
        

        
