name: cicd

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    

            
  DeployProd:
    name: Deploy to Production 
    runs-on: ubuntu-latest
    needs: [Build]
    environment: 
      name: Production 
    steps:
    - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: staging
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"

      - name: Checkout Production Branch
        run: git checkout production

      - name: Pull Production Branch
        run: git pull origin production

      - name: Merge Staging Branch
        run: git merge staging

      - name: Push to Production Branch
        run: git push origin production

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        

        
