name: cicd

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    

            
  DeployProd:
    name: Deploy to Production 
    runs-on: ubuntu-latest
    needs: [Build]
    environment: 
      name: Production 
    steps:
    - uses: actions/checkout@v3
    - name: Merge stage -> prod
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git fetch origin production
        
        # Switch to the production branch
        git checkout production
        
        # Merge the remote production branch with the local production branch
        git merge --allow-unrelated-histories origin/production
        
        # Update existing files in production branch with changes from staging
        git checkout staging -- .
        
        # Stash any unstaged changes (e.g., in the workflow file)
        git stash
        
        # Merge the staging branch into production
        git merge --allow-unrelated-histories --no-ff --no-edit origin/staging
        
        # If there are merge conflicts, resolve them manually
        
        # Add and commit the merged changes
        git add .
        git commit -m "Merge staging into production and resolve conflicts"
        
        # Push the merged changes to the remote production branch
        git push origin production
        
        # If the above push fails, try the following
        
        # Reset the production branch to the remote state
        git reset --hard origin/production
        
        # Merge the staging branch into the production branch
        git merge --allow-unrelated-histories --no-ff --no-edit origin/staging
        
        # Resolve any merge conflicts, add the changes, and commit them
        git add .
        git commit -m "Merge staging into production and resolve conflicts"
        
        # Push the merged changes to the remote production branch, forcing the push if necessary
        git push --force origin production
       
        

        
