name: cicd

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    

            
  DeployProd:
    name: Deploy to Production 
    runs-on: ubuntu-latest
    needs: [Build]
    environment: 
      name: Production 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
    
    - name: Fetch changes
      run: |
          git fetch 
          # git fetch origin staging:staging

    

    - name: Switch to production branch
      run: | 
          git checkout production
          git merge --ff-only --allow-unrelated-histories staging
          git push origin production
      
    # - name: Merge changes from staging
    #   run: git merge staging --no-edit

    # - name: Push changes to production
    #   run: git push origin production
        

        
