name: cicd

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    

            
  DeployProd:
    name: Deploy to Production 
    runs-on: ubuntu-latest
    needs: [Build]
    environment: 
      name: Production 
    steps:
    - uses: actions/checkout@v3
    - name: Merge stage -> prod
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git fetch origin production
        
        # Switch to the production branch
        git checkout production
        
        # Merge the remote production branch with the local production branch
        git merge --allow-unrelated-histories origin/production

        git checkout staging -- .
        git stash
        git stash pop
        
        # Merge the staging branch into production
        git merge --allow-unrelated-histories --no-ff --no-edit origin/staging

        git stash
        
        # Merge the staging branch into production again
        git merge --no-ff --no-edit --allow-unrelated-histories origin/staging
        
        # Reapply the stashed changes and resolve conflicts if any
        git stash pop
        
        # Add and commit the merged changes
        git add .
        git commit -m "Merge staging into production and resolve conflicts"
        
        # Push the merged changes to the remote production branch
        git push origin production
       
        

        
