name: cicd

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    

            
  DeployProd:
    name: Deploy to Production 
    runs-on: ubuntu-latest
    needs: [Build]
    environment: 
      name: Production 
    steps:
     
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --all

      - name: Switch to production branch
        run: git checkout production

      - name: Set Git user email and name
        run: |
          git config --global user.email "git@github.com"
          git config --global user.name "Shaswat19"

      - name: Merge staging into production
        run: git merge origin/staging  --allow-unrelated-histories
        
      

      - name: Merge changes from staging
        run: |
          
          git merge origin/staging --no-edit --allow-unrelated-histories
          

      - name: Push changes to production branch
        env:
            GH_PAT: ${{ secrets.GH_PAT }}
        run: git push origin production
        
