name: CI/CD (dev-to-stage)

on:
  pull_request:
    branches:
      - dev
    types:
      - closed
  push:
    branches:
      - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
        
  Integration_testing:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
      - name: List files for debugging
        run: |
          echo "Listing files in the root directory"
          ls -R
          echo "Listing files in the testing directory"
          ls -R tests

      - name: Run integration tests
        run:  pytest tests/
    continue-on-error: false


  create-pull-request:
    needs: [Integration_testing]
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true && success()

    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR 
        id: demo-1
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "dev-sprint-1.0"
          base: staging
          title: "demo for auto pr1"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: false
