name: Integration Test and Merge to Staging

on:
  pull_request:
    branches:
      - production
    types:
      - open

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
        
  Integration_testing:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
      - name: List files for debugging
        run: |
          echo "Listing files in the root directory"
          ls -R
          echo "Listing files in the testing directory"
          ls -R tests

      - name: Run integration tests
        run:  pytest tests/
    continue-on-error: false
    

  merge-on-success:
    runs-on: ubuntu-latest
    needs: [Integration_testing]  # Only run this job after integration-testing finishes
    if: ${{ needs.Integration_testing.outputs == 'success' }}  # Only run if tests pass
    steps:
      - uses: actions/checkout@v3
      - name: Merge pull request
        uses: actions/merge@v3
        with:
          branch: ${{ github.base }}
          method: squash
